// Generated by https://quicktype.io

export interface IOption {
    rows: Option[];
    totalRows: number;
    currentPage: number;
    firstPage: number;
    lastPage: number;
    totalPages: number;
}

export interface Option {
    id: string;
    name: string;
    path: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: null;
}
